// Le Congo D'Abord — Mock/Demo Data for UI rendering

import { Member, AIRecommendation, Contribution, TrainingModule, EthicsCase, InfrastructureNeed, PolicyProposal, DashboardStats } from './types';

export const MOCK_MEMBERS: Member[] = [
  {
    id: 'm-001',
    firstName: 'Marie-Claire',
    lastName: 'Kabila',
    dateOfBirth: '1985-03-15',
    gender: 'F',
    nationality: 'Congolaise',
    phone: '+243 81 234 5678',
    email: 'marie.kabila@example.com',
    location: {
      country: 'RD Congo',
      continent: 'Afrique',
      province: 'Kinshasa',
      territory: 'Gombe',
      commune: 'Gombe',
    },
    education: {
      level: 'Master',
      field: 'Sciences Politiques',
      institution: 'Université de Kinshasa (UNIKIN)',
      yearCompleted: 2010,
      score: 85,
    },
    work: {
      currentEmployer: 'ONG Femmes pour la Démocratie',
      jobTitle: 'Directrice Exécutive',
      sector: 'Société Civile',
      yearsExperience: 14,
      score: 88,
    },
    political: {
      civicOrgs: ['Réseau des Femmes pour la Démocratie', 'Comité pour la Paix'],
      localLeadershipRoles: ['Présidente du Comité de Quartier Gombe', 'Vice-Présidente ONG'],
      languagesSpoken: ['fr', 'ln', 'kg'],
      hasIntegrityCase: false,
    },
    role: 'Provincial Coordinator',
    contributionStatus: 'Active',
    memberSince: '2023-01-15',
    trainingCompletion: 90,
    integrityScore: 95,
    localCredibilityScore: 88,
    leadershipScore: 86,
  },
  {
    id: 'm-002',
    firstName: 'Jean-Baptiste',
    lastName: 'Mutombo',
    dateOfBirth: '1978-07-22',
    gender: 'M',
    nationality: 'Congolais',
    phone: '+243 99 876 5432',
    email: 'jb.mutombo@example.com',
    location: {
      country: 'RD Congo',
      continent: 'Afrique',
      province: 'Haut-Katanga',
      territory: 'Lubumbashi',
      commune: 'Lubumbashi Ville',
    },
    education: {
      level: 'Bachelor',
      field: 'Droit',
      institution: 'Université de Lubumbashi (UNILU)',
      yearCompleted: 2004,
      score: 72,
    },
    work: {
      currentEmployer: 'Cabinet Juridique Mutombo & Associés',
      jobTitle: 'Avocat Senior',
      sector: 'Juridique',
      yearsExperience: 20,
      score: 92,
    },
    political: {
      civicOrgs: ['Ordre des Avocats du Haut-Katanga', 'Conseil des Sages'],
      localLeadershipRoles: ['Ancien Coordinateur de Commune'],
      languagesSpoken: ['fr', 'sw', 'ts'],
      hasIntegrityCase: false,
    },
    role: 'National Coordinator',
    contributionStatus: 'Active',
    memberSince: '2022-11-01',
    trainingCompletion: 75,
    integrityScore: 92,
    localCredibilityScore: 85,
    leadershipScore: 90,
  },
  {
    id: 'm-003',
    firstName: 'Espérance',
    lastName: 'Lukeba',
    dateOfBirth: '1991-11-05',
    gender: 'F',
    nationality: 'Congolaise',
    phone: '+243 97 111 2233',
    email: 'esperance.lukeba@example.com',
    location: {
      country: 'RD Congo',
      continent: 'Afrique',
      province: 'Nord-Kivu',
      territory: 'Goma',
      commune: 'Goma Ville',
    },
    education: {
      level: 'Master',
      field: 'Développement International',
      institution: 'Université Catholique du Graben (UCG)',
      yearCompleted: 2016,
      score: 90,
    },
    work: {
      currentEmployer: 'UNICEF RDC',
      jobTitle: 'Coordinatrice Humanitaire',
      sector: 'Humanitaire',
      yearsExperience: 10,
      score: 85,
    },
    political: {
      civicOrgs: ['Groupe des Femmes Engagées (GFE)', 'Réseau Santé Nord-Kivu'],
      localLeadershipRoles: ['Coordo Réseau Santé', 'Présidente Association Jeunesse'],
      languagesSpoken: ['fr', 'sw', 'ln'],
      hasIntegrityCase: false,
    },
    role: 'Provincial Coordinator',
    contributionStatus: 'Active',
    memberSince: '2023-03-10',
    trainingCompletion: 85,
    integrityScore: 97,
    localCredibilityScore: 92,
    leadershipScore: 88,
  },
  {
    id: 'm-004',
    firstName: 'Patrick',
    lastName: 'Ilunga',
    dateOfBirth: '1982-04-18',
    gender: 'M',
    nationality: 'Congolais',
    phone: '+243 82 567 8901',
    email: 'p.ilunga@example.com',
    location: {
      country: 'RD Congo',
      continent: 'Afrique',
      province: 'Kasaï-Oriental',
      territory: 'Mbuji-Mayi',
      commune: 'Dibindi',
    },
    education: {
      level: 'Bachelor',
      field: 'Génie Civil',
      institution: 'Institut Supérieur des Techniques Appliquées (ISTA)',
      yearCompleted: 2007,
      score: 68,
    },
    work: {
      currentEmployer: 'Société Minière MIBA',
      jobTitle: 'Ingénieur Infrastructure',
      sector: 'Mines et Infrastructure',
      yearsExperience: 17,
      score: 80,
    },
    political: {
      previousPartyMembership: 'PPRD',
      civicOrgs: ['Association des Ingénieurs du Kasaï'],
      localLeadershipRoles: ['Chef de Quartier'],
      languagesSpoken: ['fr', 'ts', 'ln'],
      hasIntegrityCase: false,
    },
    role: 'Local Cell Leader',
    contributionStatus: 'Active',
    memberSince: '2023-06-20',
    trainingCompletion: 65,
    integrityScore: 80,
    localCredibilityScore: 82,
    leadershipScore: 75,
  },
  {
    id: 'm-005',
    firstName: 'Yvonne',
    lastName: 'Mwamba',
    dateOfBirth: '1995-08-30',
    gender: 'F',
    nationality: 'Congolaise',
    phone: '+32 475 234 567',
    email: 'y.mwamba@diaspora.be',
    location: {
      country: 'Belgique',
      continent: 'Europe',
      province: undefined,
      territory: undefined,
      commune: 'Bruxelles',
    },
    education: {
      level: 'Master',
      field: 'Relations Internationales',
      institution: 'Université Libre de Bruxelles (ULB)',
      yearCompleted: 2019,
      score: 88,
    },
    work: {
      currentEmployer: 'Union Européenne',
      jobTitle: 'Conseillère Politique Afrique',
      sector: 'Diplomatie',
      yearsExperience: 7,
      score: 82,
    },
    political: {
      civicOrgs: ['Diaspora Congolaise de Belgique', 'Forum Jeunesse Congo-Europe'],
      localLeadershipRoles: ['Présidente Diaspora Congolaise Belgique'],
      languagesSpoken: ['fr', 'ln', 'sw'],
      hasIntegrityCase: false,
    },
    role: 'Member',
    contributionStatus: 'Active',
    memberSince: '2023-09-05',
    trainingCompletion: 80,
    integrityScore: 93,
    localCredibilityScore: 60,
    leadershipScore: 82,
  },
];

export const MOCK_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: 'rec-001',
    memberId: 'm-003',
    member: MOCK_MEMBERS[2],
    targetRole: 'Provincial Deputy',
    constituency: 'Nord-Kivu — Goma',
    scores: {
      education: 90,
      workExperience: 85,
      localCredibility: 92,
      leadership: 88,
      contributionStatus: 100,
      trainingCompletion: 85,
      integrityScore: 97,
      languageAbility: 80,
      total: 88.7,
    },
    rank: 1,
    aiJustification: "Espérance Lukeba présente un profil exceptionnel pour la circonscription de Goma. Sa formation en développement international combinée à 10 ans d'expérience humanitaire avec UNICEF lui confère une connaissance approfondie des défis sécuritaires et humanitaires du Nord-Kivu. Son score d'intégrité de 97% et sa crédibilité locale élevée en font la candidate idéale pour représenter cette région stratégique.",
    generatedAt: '2024-11-15T10:30:00Z',
  },
  {
    id: 'rec-002',
    memberId: 'm-002',
    member: MOCK_MEMBERS[1],
    targetRole: 'National Deputy',
    constituency: 'Haut-Katanga — Lubumbashi',
    scores: {
      education: 72,
      workExperience: 92,
      localCredibility: 85,
      leadership: 90,
      contributionStatus: 100,
      trainingCompletion: 75,
      integrityScore: 92,
      languageAbility: 80,
      total: 85.6,
    },
    rank: 1,
    aiJustification: "Jean-Baptiste Mutombo, avec 20 ans d'expérience juridique et ses solides connections dans la région katangaise, est le candidat idéal pour représenter Lubumbashi à l'Assemblée Nationale. Sa connaissance du droit congolais et sa réputation d'intégrité lui permettront de défendre efficacement les intérêts de la province.",
    generatedAt: '2024-11-15T10:30:00Z',
  },
  {
    id: 'rec-003',
    memberId: 'm-001',
    member: MOCK_MEMBERS[0],
    targetRole: 'Provincial Deputy',
    constituency: 'Kinshasa — Gombe',
    scores: {
      education: 85,
      workExperience: 88,
      localCredibility: 88,
      leadership: 86,
      contributionStatus: 100,
      trainingCompletion: 90,
      integrityScore: 95,
      languageAbility: 80,
      total: 88.2,
    },
    rank: 1,
    aiJustification: "Marie-Claire Kabila excelle dans la gestion organisationnelle et possède une forte présence dans les réseaux féminins de Kinshasa. Sa maîtrise de trois langues (français, lingala, kikongo) et son expérience en sciences politiques font d'elle une représentante efficace pour la capitale.",
    generatedAt: '2024-11-15T10:30:00Z',
  },
];

export const MOCK_CONTRIBUTIONS: Contribution[] = [
  { id: 'c-001', memberId: 'm-001', amount: 5, currency: 'USD', date: '2024-11-01', method: 'Mobile Money', status: 'Confirmed', receiptNumber: 'CDP-2024-11-001' },
  { id: 'c-002', memberId: 'm-001', amount: 5, currency: 'USD', date: '2024-10-01', method: 'Mobile Money', status: 'Confirmed', receiptNumber: 'CDP-2024-10-001' },
  { id: 'c-003', memberId: 'm-002', amount: 5, currency: 'USD', date: '2024-11-01', method: 'Bank Transfer', status: 'Confirmed', receiptNumber: 'CDP-2024-11-002' },
  { id: 'c-004', memberId: 'm-003', amount: 5, currency: 'USD', date: '2024-11-05', method: 'Mobile Money', status: 'Confirmed', receiptNumber: 'CDP-2024-11-003' },
  { id: 'c-005', memberId: 'm-004', amount: 5, currency: 'USD', date: '2024-10-15', method: 'Cash', status: 'Confirmed', receiptNumber: 'CDP-2024-10-004' },
  { id: 'c-006', memberId: 'm-005', amount: 5, currency: 'USD', date: '2024-11-10', method: 'Online', status: 'Confirmed', receiptNumber: 'CDP-2024-11-005' },
];

export const MOCK_TRAINING_MODULES: TrainingModule[] = [
  {
    id: 'tm-001',
    title: 'Fondamentaux de la Démocratie Congolaise',
    description: 'Histoire politique, constitution, institutions démocratiques de la RDC',
    durationHours: 4,
    category: 'Political',
    level: 'Basic',
    isRequired: true,
  },
  {
    id: 'tm-002',
    title: 'Leadership Transformationnel',
    description: 'Développer des compétences de leadership pour transformer les communautés locales',
    durationHours: 6,
    category: 'Leadership',
    level: 'Intermediate',
    isRequired: true,
  },
  {
    id: 'tm-003',
    title: 'Politique Économique pour le Congo',
    description: 'Analyse des enjeux économiques, ressources naturelles, développement durable',
    durationHours: 8,
    category: 'Policy',
    level: 'Advanced',
    isRequired: false,
  },
  {
    id: 'tm-004',
    title: 'Communication Politique Efficace',
    description: 'Techniques de communication, gestion des médias sociaux, discours publics',
    durationHours: 5,
    category: 'Communication',
    level: 'Intermediate',
    isRequired: true,
  },
  {
    id: 'tm-005',
    title: 'Éthique et Intégrité Politique',
    description: 'Code de conduite, prévention de la corruption, déontologie politique',
    durationHours: 3,
    category: 'Ethics',
    level: 'Basic',
    isRequired: true,
  },
  {
    id: 'tm-006',
    title: 'Gestion des Finances Partisanes',
    description: 'Transparence financière, gestion des contributions, audit interne',
    durationHours: 4,
    category: 'Finance',
    level: 'Intermediate',
    isRequired: false,
  },
];

export const MOCK_ETHICS_CASES: EthicsCase[] = [
  {
    id: 'ec-001',
    memberId: 'm-anon-1',
    type: 'Misconduct',
    description: 'Utilisation de ressources partisanes à des fins personnelles lors d\'une réunion provinciale',
    reportedAt: '2024-10-12',
    status: 'Under Investigation',
    impactOnScore: -15,
  },
  {
    id: 'ec-002',
    memberId: 'm-anon-2',
    type: 'Fraud',
    description: 'Fausse déclaration sur les contributions mensuelles',
    reportedAt: '2024-09-05',
    status: 'Resolved',
    resolution: 'Suspension de 3 mois et remboursement exigé',
    impactOnScore: -30,
  },
  {
    id: 'ec-003',
    memberId: 'm-anon-3',
    type: 'Hate Speech',
    description: 'Discours diviseur lors d\'un meeting local',
    reportedAt: '2024-11-01',
    status: 'Open',
    impactOnScore: -20,
  },
];

export const MOCK_INFRASTRUCTURE_NEEDS: InfrastructureNeed[] = [
  {
    id: 'in-001',
    province: 'Nord-Kivu',
    territory: 'Rutshuru',
    category: 'Healthcare',
    severity: 'Critical',
    description: 'Hôpital central détruit — 500 000 personnes sans accès aux soins de santé de base',
    estimatedCost: 2500000,
    populationAffected: 500000,
  },
  {
    id: 'in-002',
    province: 'Kasaï-Oriental',
    territory: 'Mbuji-Mayi',
    category: 'Electricity',
    severity: 'High',
    description: 'Coupures d\'électricité chroniques affectant les entreprises et ménages',
    estimatedCost: 15000000,
    populationAffected: 2100000,
  },
  {
    id: 'in-003',
    province: 'Équateur',
    territory: 'Mbandaka',
    category: 'Roads',
    severity: 'Critical',
    description: 'Route nationale 1 impraticable — isolation totale de plusieurs territoires pendant la saison des pluies',
    estimatedCost: 8000000,
    populationAffected: 800000,
  },
  {
    id: 'in-004',
    province: 'Ituri',
    category: 'Water',
    severity: 'Critical',
    description: 'Accès à l\'eau potable inférieur à 20% de la population — risque de choléra élevé',
    estimatedCost: 3000000,
    populationAffected: 3500000,
  },
  {
    id: 'in-005',
    province: 'Tanganyika',
    territory: 'Kalemie',
    category: 'Internet',
    severity: 'Medium',
    description: 'Couverture internet inexistante — isolement numérique des communautés',
    estimatedCost: 500000,
    populationAffected: 1200000,
  },
];

export const MOCK_POLICY_PROPOSALS: PolicyProposal[] = [
  {
    id: 'pp-001',
    title: "Plan National de Développement des Énergies Renouvelables",
    category: 'Énergie',
    description: 'Mise en place de micro-réseaux solaires dans les zones rurales non connectées au réseau national',
    targetBeneficiaries: '15 millions de Congolais dans 12 provinces',
    estimatedImpact: 'Réduction de 40% du déficit énergétique en 5 ans',
    aiSummary: "L'IA recommande prioriser les provinces du Kasaï et de l'Équateur où l'ensoleillement est optimal et le déficit le plus critique.",
    createdAt: '2024-11-10',
  },
  {
    id: 'pp-002',
    title: "Programme National de Digitalisation des Services Publics",
    category: 'Technologie',
    description: 'Numérisation des registres d\'état civil, permis, et services administratifs',
    targetBeneficiaries: 'Tous les citoyens congolais',
    estimatedImpact: 'Réduction de la corruption administrative de 60%, gain d\'efficacité de 80%',
    aiSummary: "Priorité : Kinshasa, Lubumbashi, et Goma comme villes pilotes. Extension nationale en 3 phases sur 4 ans.",
    createdAt: '2024-10-25',
  },
  {
    id: 'pp-003',
    title: "Réforme du Secteur Agricole pour la Souveraineté Alimentaire",
    category: 'Agriculture',
    description: 'Mécanisation, formation des agriculteurs, accès aux marchés et financement rural',
    targetBeneficiaries: '8 millions d\'agriculteurs congolais',
    estimatedImpact: 'Doublement de la production agricole en 5 ans, réduction de l\'importation alimentaire de 35%',
    aiSummary: "Axe prioritaire : provinces du Bandundu (Kwilu, Kwango, Maï-Ndombe) à fort potentiel agricole inexploité.",
    createdAt: '2024-11-05',
  },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalMembers: 34750,
  membersByProvince: {
    'Kinshasa': 4250,
    'Haut-Katanga': 2380,
    'Nord-Kivu': 2140,
    'Kasaï-Oriental': 1280,
    'Kwilu': 1680,
    'Kasaï-Central': 1140,
    'Sud-Kivu': 1620,
    'Kongo Central': 1850,
    'Ituri': 1480,
    'Tshopo': 880,
  },
  activeContributors: 25120,
  monthlyRevenue: 125600,
  electionReadinessIndex: 58,
  topCandidates: MOCK_RECOMMENDATIONS,
  integrityAlerts: 3,
  infrastructureNeeds: 47,
  trainingCompletion: 72,
};
